# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f8fa7ff2dd1c4228af5e650f0f43e75140acc21378afb9688b620db2c4b6d2fb349ebd452cc123e4ceb8d516df52c50a03f7efbae2ab50c34c7e35b07571ef3

test:
  secret_key_base: 8cedfab6f70328a070449e9e0429a684588cb5634af32a0d2509faaa21e8b886271c8801ba268f4819e61e3e2f0e9b9998093b4f582c47f9cd8bd6c2b351f03f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
